<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useLobbyStore } from '@/stores/lobby'
import { useMediaStore, type MediaTrack } from '@/stores/media'
const auth=useAuthStore(),lobby=useLobbyStore(),media=useMediaStore();const musicOpen=ref(false),shortsOpen=ref(false),query=ref(''),results=ref<MediaTrack[]>([]),searching=ref(false),shortQuery=ref(''),shortFeed=ref<MediaTrack[]>([]),shortIndex=ref(0),shorting=ref(false),playerHost=ref<HTMLElement|null>(null),player=ref<any>(null),lastVideo=ref<string|null>(null),volume=ref(Number(localStorage.getItem('royal.music.volume')||55)),muted=ref(false),unlocked=ref(sessionStorage.getItem('royal.music.unlocked')==='1')
const roomId=computed(()=>lobby.currentRoom?.id||null),isHost=computed(()=>!!lobby.currentRoom&&lobby.currentRoom.hostUserId===auth.user?.id),currentShort=computed(()=>shortFeed.value[shortIndex.value]||null)
function expected(){const s=media.state;if(!s?.current)return 0;if(s.playing&&s.startedAtUtc)return Math.max(0,(Date.now()-new Date(s.startedAtUtc).getTime())/1000);return Math.max(0,s.positionSeconds||0)}
async function loadYT(){const w=window as any;if(w.YT?.Player)return;if(!document.getElementById('youtube-iframe-api')){const tag=document.createElement('script');tag.id='youtube-iframe-api';tag.src='https://www.youtube.com/iframe_api';document.body.appendChild(tag)}await new Promise<void>(resolve=>{const t=window.setInterval(()=>{if((window as any).YT?.Player){window.clearInterval(t);resolve()}},200)})}
async function initPlayer(){if(player.value||!playerHost.value)return;await loadYT();const YT=(window as any).YT;player.value=new YT.Player(playerHost.value,{width:'100%',height:'190',playerVars:{playsinline:1,rel:0,modestbranding:1},events:{onReady:(e:any)=>{e.target.setVolume(volume.value);if(muted.value)e.target.mute()}}})}
async function syncPlayer(){if(!musicOpen.value)return;await nextTick();await initPlayer();const p=player.value,s=media.state;if(!p||!s?.current||!unlocked.value)return;const pos=expected();try{if(lastVideo.value!==s.current.videoId){s.playing?p.loadVideoById({videoId:s.current.videoId,startSeconds:pos}):p.cueVideoById({videoId:s.current.videoId,startSeconds:pos});lastVideo.value=s.current.videoId}else{const local=p.getCurrentTime?.()||0;if(Math.abs(local-pos)>3.5)p.seekTo?.(pos,true);s.playing?p.playVideo?.():p.pauseVideo?.()}p.setVolume?.(volume.value);muted.value?p.mute?.():p.unMute?.()}catch{/* player warming */}}
watch(roomId,async(next,prev)=>{if(prev&&prev!==next)await media.leaveRoom();if(next)try{await media.joinRoom(next)}catch{/* media optional */}},{immediate:true});watch(()=>media.state?.revision,()=>void syncPlayer());watch(musicOpen,v=>{if(v)void syncPlayer()});watch(volume,v=>{localStorage.setItem('royal.music.volume',String(v));player.value?.setVolume?.(v)})
async function enable(){unlocked.value=true;sessionStorage.setItem('royal.music.unlocked','1');await syncPlayer()}
async function search(){if(!query.value.trim()||!isHost.value)return;searching.value=true;try{results.value=await media.search(query.value.trim())}finally{searching.value=false}}
async function choose(track:MediaTrack){await enable();await media.select(track);results.value=[]}
async function toggle(){const p=player.value;let pos=expected();try{pos=p?.getCurrentTime?.()??pos}catch{}await media.toggle(!media.state?.playing,pos)}
async function findShorts(){if(!shortQuery.value.trim())return;shorting.value=true;try{shortFeed.value=await media.search(shortQuery.value.trim(),true);shortIndex.value=0}finally{shorting.value=false}}
function nextShort(delta:number){if(!shortFeed.value.length)return;shortIndex.value=(shortIndex.value+delta+shortFeed.value.length)%shortFeed.value.length}
onBeforeUnmount(()=>{void media.leaveRoom();try{player.value?.destroy?.()}catch{}})
</script>
<template><div v-if="roomId" class="media-dock"><div class="media-buttons"><button @click="musicOpen=!musicOpen">🎵 {{ media.state?.current?.title||'Music Room' }}</button><button @click="shortsOpen=!shortsOpen">📱 Shorts</button></div>
<section v-if="musicOpen" class="media-panel music-panel"><header><b>TABLE MUSIC</b><span>{{ isHost?'Bạn là DJ':'DJ: Chủ bàn' }}</span><button @click="musicOpen=false">×</button></header><div class="yt-box"><div ref="playerHost" class="yt-player"/><button v-if="media.state?.current&&!unlocked" class="unlock" @click="enable">🎧 Bật nhạc bàn</button><p v-if="!media.state?.current">Chủ bàn chưa chọn nhạc</p></div><div v-if="media.state?.current" class="now"><b>{{ media.state.current.title }}</b><small>{{ media.state.current.channelTitle||'YouTube' }}</small></div><div class="controls"><button :disabled="!isHost||!media.state?.current" @click="toggle">{{ media.state?.playing?'⏸':'▶' }}</button><button :disabled="!isHost||!media.state?.current" @click="media.next()">⏭</button><button @click="muted=!muted;syncPlayer()">{{ muted?'🔇':'🔊' }}</button><input v-model.number="volume" type="range" min="0" max="100"></div><div v-if="isHost" class="search"><input v-model="query" placeholder="Tìm YouTube..." @keyup.enter="search"><button :disabled="searching" @click="search">{{ searching?'...':'Tìm' }}</button></div><div v-if="results.length" class="results"><button v-for="r in results" :key="r.videoId" @click="choose(r)"><img :src="r.thumbnail"><span><b>{{ r.title }}</b><small>{{ r.channelTitle }}</small></span></button></div><div v-if="media.state?.queue.length" class="queue"><span>Queue {{ media.state.queue.length }}/20</span><button v-if="isHost" @click="media.clearQueue()">Xóa queue</button><button v-for="q in media.state.queue" :key="q.videoId" disabled>{{ q.title }}</button></div></section>
<section v-if="shortsOpen" class="media-panel shorts-panel"><header><b>SHORTS LOUNGE</b><span>{{ shortFeed.length?`${shortIndex+1}/${shortFeed.length}`:'Tìm chủ đề' }}</span><button @click="shortsOpen=false">×</button></header><div class="short-frame"><iframe v-if="currentShort" :key="currentShort.videoId" :src="`https://www.youtube.com/embed/${currentShort.videoId}?autoplay=1&playsinline=1&rel=0`" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen/><p v-else>Tìm “meme việt”, “football”, “remix”...</p></div><div v-if="currentShort" class="now"><b>{{ currentShort.title }}</b><small>{{ currentShort.channelTitle }}</small></div><div class="controls"><button :disabled="shortFeed.length<2" @click="nextShort(-1)">↑ Trước</button><button :disabled="shortFeed.length<2" @click="nextShort(1)">Tiếp ↓</button></div><div class="search"><input v-model="shortQuery" placeholder="Chủ đề Shorts..." @keyup.enter="findShorts"><button :disabled="shorting" @click="findShorts">{{ shorting?'...':'Tìm' }}</button></div></section></div></template>
<style scoped>.media-dock{position:fixed;right:14px;bottom:14px;z-index:80;font-family:Inter,system-ui,sans-serif}.media-buttons{display:flex;gap:8px;justify-content:flex-end}.media-buttons button,.media-panel button{border:1px solid rgba(244,208,111,.35);background:#102c26;color:#f6e6b4;border-radius:10px;padding:8px 10px}.media-panel{position:absolute;right:0;bottom:46px;width:min(360px,calc(100vw - 20px));max-height:min(72vh,620px);overflow:auto;background:rgba(6,24,21,.98);border:1px solid rgba(244,208,111,.45);box-shadow:0 20px 50px #0009;border-radius:16px;padding:12px;color:#f8efd2}.media-panel header{display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:center}.media-panel header span{font-size:12px;opacity:.7}.yt-box,.short-frame{margin-top:10px;min-height:190px;background:#020807;border-radius:12px;display:grid;place-items:center;position:relative;overflow:hidden}.yt-player,.short-frame iframe{width:100%;height:190px;border:0}.unlock{position:absolute}.now{display:grid;gap:2px;margin:10px 0}.now small{opacity:.65}.controls,.search{display:flex;gap:8px;align-items:center;margin-top:8px}.controls input{flex:1}.search input{min-width:0;flex:1;background:#071c18;border:1px solid #ffffff22;color:white;border-radius:9px;padding:9px}.results{display:grid;gap:6px;margin-top:8px}.results button{display:flex;text-align:left;gap:8px}.results img{width:80px;height:45px;object-fit:cover;border-radius:6px}.results span{display:grid}.results b{font-size:12px}.results small{font-size:10px;opacity:.65}.queue{display:grid;gap:5px;margin-top:10px}.short-frame{height:360px}.short-frame iframe{height:360px}@media(max-width:600px){.media-dock{right:8px;bottom:8px}.media-panel{width:calc(100vw - 16px);max-height:70vh}.short-frame,.short-frame iframe{height:52vh}}</style>
